### ISSUE TITLE
File Field is Broken on Add New Download Page

### ISSUE THREAD

**Issue by ghost** [BeardedGinger/download-gate-gravityforms#8]
It looks like there is a PHP error related to CMB2 that is causing the file field to break. I have tested this with the current version of WordPress using the twentyseventeen theme.

<img width="1140" alt="screen shot 2018-09-12 at 1 48 18 pm" src="https://user-images.githubusercontent.com/43218632/45446950-d97b8a00-b693-11e8-8f90-dc68ce5b1881.png">

**Comment by ghost** [comment]
+1 here

**Comment by ethanclevenger91** [comment]
The version of CMB2 bundled with the plugin has a fatal error in it. Of course, this has been fixed in the latest version of CMB2.

You can [check out my fork](https://github.com/ethanclevenger91/download-gate-gravityforms) and use it, should be just fine.

This repo uses git submodules, so don't forget the `--recursive` flag when you check out:

```git clone --recursive https://github.com/ethanclevenger91/download-gate-gravityforms```

**Comment by MylesBecker** [comment]
@ethanclevenger91 - I went to the fork you linked, downloaded the ZIP, and installed it on my website. I also installed and activated the latest version of CMB2.

When I went to activate the main plugin, I got an error that I'm hoping you can help me with:

Plugin could not be activated because it triggered a fatal error.

Warning: require(/www/wp-content/plugins/download-gate-gravityforms-master/includes/../resources/CPT_Core/CPT_Core.php): Failed to open stream: No such file or directory in /www/wp-content/plugins/download-gate-gravityforms-master/includes/CPT.php on line 101 Fatal error: Uncaught Error: Failed opening required '/www/wp-content/plugins/download-gate-gravityforms-master/includes/../resources/CPT_Core/CPT_Core.php' (include_path='.:/usr/share/php') in /www/wp-content/plugins/download-gate-gravityforms-master/includes/CPT.php:101 Stack trace: #0 /www/wp-content/plugins/download-gate-gravityforms-master/includes/CPT.php(46): LC_Gforms_Download_Gate\CPT\CPT->get_cpt_core_class() #1 /www/wp-content/plugins/download-gate-gravityforms-master/includes/Main.php(41): LC_Gforms_Download_Gate\CPT\CPT->register_cpt() #2 /www/wp-content/plugins/download-gate-gravityforms-master/download-gate-gravityforms.php(125): LC_Gforms_Download_Gate\Main->run() #3 /www/wp-content/plugins/download-gate-gravityforms-master/download-gate-gravityforms.php(129): run_gravityforms_download_gate() #4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/www/wp-content...') #5 /wordpress/wp-admin/plugins.php(194): plugin_sandbox_scrape('download-gate-g...') #6 {main} thrown in /www/wp-content/plugins/download-gate-gravityforms-master/includes/CPT.php on line 101

Thanks, in advance.
